### ISSUE TITLE
Show partial matches for part numbers

### ISSUE THREAD

**Issue by kevinb456** [kitspace/bom-builder#22] opened 2019-04-05 17:38 UTC
e.g. "Bourns MF-MSMF200" find no results, but reasonable to be in a BOM because this is the number in the main datasheet table. The full orderable part includes a packaging code "MF-MSMF200-2".

May need an indication to the user that this is not a direct match.

**Comment by kasbah** [comment] 2019-04-05 20:14
Duplicate of #7

**Closed by kasbah** 2019-04-05 20:14 UTC
